name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}          # Ví dụ: 167.99.78.5
          username: ${{ secrets.VPS_USER }}        # Tên đăng nhập SSH trên VPS
          key: ${{ secrets.VPS_SSH_KEY }}          # Private key dưới dạng string, thêm vào Secrets của GitHub
          script: |
            cd /path/to/devbaooPortfolio       # Thay đổi đường dẫn đến thư mục dự án trên VPS
            git pull origin main               # Cập nhật code mới nhất
            npm install                        # Cài đặt lại dependencies nếu cần
            npm run build                      # Build lại dự án
            # Khởi động lại ứng dụng với PM2 (hoặc lệnh deploy của bạn)
            pm2 restart devbaooPortfolio || pm2 start npm --name "devbaooPortfolio" -- run start
