name: Deploy Next.js App

on:
  push:
    branches:
      - main  # Hoặc branch bạn muốn deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Thiết lập Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Sử dụng phiên bản Node.js bạn mong muốn

      # 3. Cài đặt các package cần thiết
      - name: Install dependencies
        run: npm install

      # 4. Build ứng dụng
      - name: Build project
        run: npm run build

      # 5. Deploy lên VPS qua SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}       # Địa chỉ IP hoặc tên miền của VPS
          username: ${{ secrets.VPS_USER }}     # Tên đăng nhập SSH trên VPS
          key: ${{ secrets.VPS_KEY }}           # Private key SSH (đã thêm vào GitHub Secrets)
          port: ${{ secrets.VPS_PORT }}         # Cổng SSH (mặc định là 22)
          script: |
            cd /var/www/devbaooPortfolio
            git pull
            npm install
            npm run build
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- run start
