name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}         
          username: ${{ secrets.VPS_USER }}        
          key: ${{ secrets.VPS_SSH_KEY }}          
          script: |
            export PATH="/root/.nvm/versions/node/v20.18.3/bin:$PATH"
            cd /var/www/devbaooPortfolio       # Thay đổi đường dẫn đến thư mục dự án trên VPS
            git pull origin main               # Kéo code mới nhất
            npm install                        # Cài đặt lại dependencies nếu cần
            npm run build                      # Build lại dự án trên VPS
            pm2 restart devbaooPortfolio

